### ISSUE TITLE
Update out-of-date documentation

### ISSUE THREAD

**Issue by maurizi** [azavea/python-omgeo#39]
The current version of the documentation on Read The Docs appears to be either `1.6.0` or `1.7.2` (the version number in the upper left says `1.6.0`, but the release notes page has `1.7.2` as the latest version).

Either way, these are both out-of-date, as the most recent version is `2.0.1`.

https://python-omgeo.readthedocs.io/en/latest/

**Comment by maurizi** [comment]
The mismatch in versions between the release notes page and the main version number appears to be because the version number is hardcoded: https://github.com/azavea/python-omgeo/blob/32f8b4cef6d202f50c2174ff5bc7c0f862febb99/sphinx/conf.py#L51

**Comment by flibbertigibbet** [comment]
Issue is that the [Read the Docs builds have been failing](https://readthedocs.org/projects/python-omgeo/builds/); the version number in Sphinx was updated on the last release, but the docs still did not update.

**Comment by flibbertigibbet** [comment]
Fixed in #47 by adding an empty `requirements.txt` to fix the Read the Docs build.
