### ISSUE TITLE
No data (matches) with python 3.5.2 and urllib 1.13.1

### ISSUE THREAD

**Issue by mbtronics** [azavea/python-omgeo#50]
On a certain computer, I never get any matches.
python version: 3.5.2 and urllib 1.13.1
These are the latest on Ubuntu 16.04.4 LTS .

Code works perfectly on more recent versions.
I have found the solution and will make a pull request shortly.

**Comment by hectcastro** [comment]
It is possible that this issue has not been resolved by the migration to Requests in https://github.com/azavea/python-omgeo/pull/53. Please feel free to reopen if that is not the case.
